apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator-hw
spec:
  selector:
    matchLabels:
      app: loadgenerator-hw
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgenerator-hw
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      containers:
      - name: main
        # Replace below with path to your load generator container
        image: us-docker.pkg.dev/${PROJECT}/demos/hello-operations-demo:latest
        env:
        - name: FRONTEND_ADDR
          value: "http://hello-logging-service:80"
        - name: APP_ROUTE
          value: "/random-error"
        # Current configuration will generate 1 RPS per user, per pod
        - name: USERS
          value: "50"
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
